---
title: 'Exercise 2: Physical environmental controls on landcover pattern'
author: "Marie Bouffard"
date: "1/20/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(entropy)
library(dplyr)
library(here)
library(ggraph)

```

### Mutual Information Analysis Santa Ynez
```{r}

# Read in sample data and remove missing data
sydat <- read.csv(here("Exercise_2_Physical_Controls", "ex2_sample_data2.csv"), 
                  header = TRUE,
                  na.strings = c(-9999)) %>% 
  na.omit()

```
<br>

#### First level MIA

```{r}

# Calculate joint entropy of landcover with geology, flow accumulation and #winter insolation

migeol <- table(sydat$landcover,sydat$geology) %>% mi.empirical()

miflow <- table(sydat$landcover,sydat$flowaccum) %>% mi.empirical()

mirad <- table(sydat$landcover,sydat$winter_rad) %>% mi.empirical()

#---------------------------------------
# Tier 1
#---------------------------------------

tier1 <- table(sydat$landcover, sydat$geology) %>% 
  as.data.frame.matrix()

sum(tier1[,"1"])
sum(tier1[,"2"])
sum(tier1[,"3"])
sum(tier1[,"4"])
sum(tier1[,"5"])

#---------------------------------------
# Tier 2
#---------------------------------------

# Class 1
tier2_geo1 <- sydat %>% 
  filter(geology == "1")

geo1 <- table(tier2_geo1$landcover,tier2_geo1$winter_rad)
  
sum(geo1[,"1"])
sum(geo1[,"2"])
sum(geo1[,"3"])

# Class 2
tier2_geo2 <- sydat %>% 
  filter(geology == "2")

geo2 <- table(tier2_geo2$landcover,tier2_geo2$winter_rad)
  
sum(geo2[,"1"])
sum(geo2[,"2"])
sum(geo2[,"3"])

# Class 3
tier2_geo3 <- sydat %>% 
  filter(geology == "3")

geo3 <- table(tier2_geo3$landcover,tier2_geo3$winter_rad)
  
sum(geo3[,"1"])
sum(geo3[,"2"])
sum(geo3[,"3"])

# Class 4
tier2_geo4 <- sydat %>% 
  filter(geology == "4")

geo4 <- table(tier2_geo4$landcover,tier2_geo4$winter_rad)
  
sum(geo4[,"1"])
sum(geo4[,"2"])
sum(geo4[,"3"])

# Class 5
tier2_geo5 <- sydat %>% 
  filter(geology == "5")

geo5 <- table(tier2_geo5$landcover,tier2_geo5$winter_rad)
  
sum(geo5[,"1"])
sum(geo5[,"2"])
sum(geo5[,"3"])

```

Highest association is between landcover and geology (MI=0.2286).

<br>

#### Second level MIA
```{r}

# Next, stratify the sample by geology loop through geology classes 1 to 5, and calculate MI for flowaccum and winter_rad

mi_flow2 <- NULL
    		for(i in c(1:5)){
       			y <- filter(sydat,geology == i)
        		x <- table(y$landcover,y$flowaccum) %>% mi.empirical()
      		mi_flow2 <- c(mi_flow2,x)
    		}

mi_rad2 <- NULL
    		for(i in c(1:5)){
        			y <- filter(sydat,geology == i)
        			x <- table(y$landcover,y$winter_rad) %>% mi.empirical()
    		mi_rad2 <- c(mi_rad2,x)
    		}

mi_rad2

```

How strong is the relationship between land cover and physical environmental variables?

```{r}

#---------------------------------------
# entropy
#---------------------------------------

entropy.empirical(sydat$landcover)

#Geology
g1 <- entropy.empirical(sydat[sydat[,6]==1,5])
g2 <- entropy.empirical(sydat[sydat[,6]==2,5])
g3 <- entropy.empirical(sydat[sydat[,6]==3,5])
g4 <- entropy.empirical(sydat[sydat[,6]==4,5])
g5 <- entropy.empirical(sydat[sydat[,6]==5,5])

# Geo portion

g_prop <- table(sydat$geology)/length(sydat$landcover)

g_weight <- sum(g1*g_prop[1], g2*g_prop[2], g3*g_prop[3], g4*g_prop[4], g5*g_prop[5])

table(sydat$landcover, sydat$geology)

# Flow
f1 <- entropy.empirical(sydat[sydat[,7]==1,5])
f2 <- entropy.empirical(sydat[sydat[,7]==2,5])
f3 <- entropy.empirical(sydat[sydat[,7]==3,5])

# Flow portion

f_prop <- table(sydat$flowaccum)/length(sydat$landcover)

f_weight <- sum(f1*f_prop[1], f2*f_prop[2], f3*f_prop[3])

table(sydat$landcover, sydat$flowaccum)

# Winter rad
r1 <- entropy.empirical(sydat[sydat[,8]==1,5])
r2 <- entropy.empirical(sydat[sydat[,8]==2,5])
r3 <- entropy.empirical(sydat[sydat[,8]==3,5])

# rad portion

r_prop <- table(sydat$winter_rad)/length(sydat$landcover)

r_weight <- sum(r1*r_prop[1], r2*r_prop[2], r3*r_prop[3])

table(sydat$landcover, sydat$winter_rad)

#---------------------------------------
# redundancy
#---------------------------------------

# calculate redundancy (R) = 1 - (weighted entropy of your second variable)/(total entropy from your first variable)

g_red <- 1 - (g_weight)/entropy.empirical(sydat$landcover)

f_red <- 1 - (f_weight)/entropy.empirical(sydat$landcover)

r_red <- 1 - (r_weight)/entropy.empirical(sydat$landcover)

```
